### ISSUE TITLE
props is not defined

### ISSUE THREAD

**Issue by jmikedupont2** [magic-examples/example#29]
```
./node_modules/.bin/magic dev --watch src
prepare 558.8ms
props is not defined
ReferenceError: props is not defined
    at View (file:///home/mdupont/dev/example/node_modules/@magic/core/src/modules/Logo.mjs:2:15)
    at View (file:///home/mdupont/dev/example/node_modules/@magic/core/src/modules/Header.mjs:11:27)
    at View (file:///home/mdupont/dev/example/node_modules/@magic/core/src/modules/Router.mjs:17:7)
    at file:///home/mdupont/dev/example/node_modules/@magic/core/src/modules/app.mjs:215:13
    at file:///home/mdupont/dev/example/node_modules/@magic/core/src/tasks/transpile/html.mjs:26:44
    at Array.map (<anonymous>)
    at default (file:///home/mdupont/dev/example/node_modules/@magic/core/src/tasks/transpile/html.mjs:19:20)
    at Module.transpile (file:///home/mdupont/dev/example/node_modules/@magic/core/src/tasks/transpile/index.mjs:32:17)
    at async runCmd (file:///home/mdupont/dev/example/node_modules/@magic/core/src/cluster/runCmd.mjs:8:18)
    at async build (file:///home/mdupont/dev/example/node_modules/@magic/core/src/cluster/build.mjs:13:55)
 Page url: /
exit 1
```

**Comment by jaeh** [comment]
thanks for the issue, sorry for the late answer, have been incredibly busy with another project lately.

i just pushed a new version, maybe retry, `npm install` will be required after pulling.
